In [1]:
import numpy as np

In [2]:
a = np.array([[0.2,0.8], [0.3, 0.7]])
pi = np.array([0.6, 0.4])
e = np.array([[0.1,0.9], [0.5, 0.5]])

In [3]:
ss = np.array([0,0,1])
v = np.array([0,1,1])
t = len(ss)

In [4]:
# joint probability of p(h1:d, v1:d)

total_joint = pi[ss[0]] * e[ss[0], v[0]]
for i in range(1, t):
    total_joint = total_joint * a[ss[i-1], ss[i]] * e[ss[i], v[i]]
print('total joint', total_joint)

total joint 0.00432


In [5]:
import itertools

# marginal probability in naive way p(v1:d)
# calculate the sum of the transition probabilities

possible_ss = np.array(list(itertools.product([0, 1], repeat=3)))
possible_ss_prob = 0
for psi in range(possible_ss.shape[0]):
    ps = possible_ss[psi]
    print(ps)
    ps_prob = pi[ps[0]]
    for i in range(1, t):
        ss_prob = ps_prob * a[ps[i-1], ps[i]]
    possible_ss_prob += ps_prob

print('marginal p(v1:d) = ', total_joint / possible_ss_prob)

[0 0 0]
[0 0 1]
[0 1 0]
[0 1 1]
[1 0 0]
[1 0 1]
[1 1 0]
[1 1 1]
marginal p(v1:d) =  0.0010800000000000002


In [9]:
# now use dynamic programing / forward algorithm
# the forward algorithm calculates the marginal likelihood of the state given the observations up to that time
# however it is un-normalised

def alpha_discrete(obs, pi, A, B):
    # obs: observed sequence of length T
    # pi: initial state probabilities of length N
    # A: state transition matrix of size N x N
    # B: observation matrix of size N x M

    T = len(obs)   # length of the observed sequence
    N = len(pi)    # number of states in the model
    alpha = np.zeros((T, N))   # initialize alpha variable with zeros

    # Compute alpha values for the first time step (t = 0)
    alpha[0, :] = pi * B[:, obs[0]]

    # Recursively compute alpha values for each time step (t = 1, 2, ..., T-1)
    for t in range(1, T):
        for j in range(N):
            alpha[t, j] = np.sum(alpha[t-1, :] * A[:, j]) * B[j, obs[t]]

    return alpha

In [8]:
e[ss[0]]

array([0.1, 0.9])